Repository openshift/ironic-image, pull requests merged in 2019-08, with the labels that each got.

#11 Trigger an image build.
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#10 Account for different upstream/downstream ipxe filenames
  Dockerfile.ocp
  prepare-ipxe.sh
Labels: approved, lgtm, size/S

#12 Bug 1737086: Sync master fixes to release-4.2
  Dockerfile.ocp
  prepare-ipxe.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#13 Dummy change to force CI to build
  README.md
Labels: approved, lgtm, size/XS

#14 Disable listening for DNS
  dnsmasq.conf
Labels: approved, lgtm, size/XS

#15 Wait for provisioning interface and db sync
  Dockerfile
  Dockerfile.ocp
  configure-ironic.sh
  rundnsmasq.sh
  runhttpd.sh
  runironic-conductor.sh
Labels: approved, lgtm, size/S
