Repository openshift/ironic-image, pull requests merged in 2019-11, with the labels that each got.

#31 Enable fast_track provisioning for nodes
  configure-ironic.sh
Labels: approved, lgtm, size/XS

#27 Enable prometheus-exporter
  Dockerfile.ocp
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
  runironic-exporter.sh
Labels: approved, lgtm, size/S

#33 Bug 1778237: apply latest changes to 4.3
  Dockerfile.ocp
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
  runironic-exporter.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/M
