Repository openshift/ironic-image, pull requests merged in 2019-07, with the labels that each got.

#1 Apply latest changes from metal3-io
  Dockerfile
  README.md
  configure-ironic.sh
  dnsmasq.conf
  inspector.ipxe
  installexporter.sh
  rundnsmasq.sh
  runexporterapp.sh
  runhttpd.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic-exporter.sh
  runironic.sh
  runmariadb.sh
Labels: size/L

#3 Add Dockerfile.ocp
  Dockerfile.ocp
Labels: size/M

#4 Build container from rhel7
  Dockerfile.ocp
Labels: lgtm, size/XS

#2 Merge latest changes from upstream
  Dockerfile
  configure-ironic.sh
  ironic.conf
  runironic-api.sh
Labels: size/L

#5 Adding OWNERS file
  OWNERS
Labels: size/S

#6 Merge latest changes from upstream
  Dockerfile
  configure-ironic.sh
  runexporterapp.sh
Labels: lgtm, size/XS

#7 Merge latest changes from upstream
  Dockerfile
  configure-ironic.sh
  inspector.ipxe
  ironic.conf
  runexporterapp.sh
  runironic-exporter.sh
  runironic.sh
Labels: lgtm, size/M

#8 Update Dockerfile.ocp for Ironic Stein
  Dockerfile.ocp
Labels: size/S

#9 Fix dockerfile.ocp for upstream openshift image builds
  Dockerfile.ocp
Labels: size/XS
