Repository openshift/ironic-image, pull requests merged in 2020-10, with the labels that each got.

#107 Bug 1884155: Explicitly set json_rpc.auth_strategy to noauth
  configure-ironic.sh
  ironic.conf
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#106 Bug 1862608: Install and configure for syslinux-nonlinux
  ironic.conf
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#108 Updating ironic builder & base images to be consistent with ART
  Dockerfile.ocp
Labels: approved, lgtm

#109 Re-enable automated_clean
  ironic.conf
Labels: approved, lgtm

#110 Sync upstream patches down to openshift
  Dockerfile.ocp
  README.md
  configure-ironic.sh
  inspector.ipxe
  ironic-common.sh
  ironic.conf
  ironic.conf.j2
  main-packages-list.txt
  runhttpd.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
Labels: approved, lgtm

#111 Revert "Bug 1862608: Install and configure for syslinux-nonlinux"
  ironic.conf.j2
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#112 Bug 1862608: Install syslinux-nonlinux
  Dockerfile.ocp
  ironic.conf.j2
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#113 Use [] around IPv6 address for conductor host config
  ironic.conf.j2
Labels: approved, lgtm
