Repository openshift/ironic-image, pull requests merged in 2020-01, with the labels that each got.

#46 Remove unused Dockerfile
  Dockerfile
Labels: approved, lgtm, size/M

#45 Sync IPv6 and Optional DHCP Changes from Upstream
  Dockerfile.ocp
  configure-ironic.sh
  dnsmasq.conf
  dnsmasq.conf.j2
  ironic-common.sh
  rundnsmasq.sh
  runhealthcheck.sh
  runhttpd.sh
Labels: approved, lgtm, size/L

#44 Install python3-sushy-oem-idrac
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#48 Add all interfces currently supported
  ironic.conf
Labels: approved, lgtm, size/XS

#50 Bug 1796141: Temporarily disable cleaning as a workaround
  ironic.conf
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
