Repository openshift/ironic-image, pull requests merged in 2020-04, with the labels that each got.

#69 virtmedia fixes
  Dockerfile.ocp
  ironic.conf
Labels: approved, lgtm

#70 Virtmedia fixes2
  Dockerfile.ocp
  ironic.conf
Labels: approved

#71 Bug 1814901: Disable default gateway for provisioning network in IPv6
  dnsmasq.conf.j2
Labels: approved, bugzilla/valid-bug, lgtm

#73 Bug 1822763: Increase command retries and add PXE booting retries
  ironic.conf
Labels: approved, bugzilla/urgent, bugzilla/valid-bug, lgtm

#75 Add bugzilla component information to OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm
