Repository openshift/ironic-image, pull requests merged in 2020-03, with the labels that each got.

#54 Bug 1807633: Copy snpnoly.efi to tftpboot directory
  Dockerfile.ocp
  prepare-ipxe.sh
  rundnsmasq.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#56 Bug 1807634: Copy iPXE images to tftpboot directory including snponly.efi
  prepare-ipxe.sh
  rundnsmasq.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#58 Add schema to bootloader setting
  ironic.conf
Labels: approved, lgtm, size/XS

#63 Stop log files + Remove iptables filters
  Dockerfile.ocp
  rundnsmasq.sh
  runhttpd.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
  runmariadb.sh
Labels: approved, lgtm, size/M

#64 Bug 1810485: Stop log files + Remove iptables filters
  Dockerfile.ocp
  rundnsmasq.sh
  runhttpd.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
  runmariadb.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#60 Add WORKDIR to builder
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#62 Bug 1810145: Add WORKDIR to builder
  Dockerfile.ocp
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#57 Remove custom healthchecks
  Dockerfile.ocp
  rundnsmasq.sh
  runhealthcheck.sh
  runhttpd.sh
  runironic.sh
Labels: approved, lgtm, size/M

#59 Bug 1809658: Add schema to bootloader setting
  ironic.conf
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#66 Bug 1811573: Remove custom healthchecks
  Dockerfile.ocp
  rundnsmasq.sh
  runhealthcheck.sh
  runhttpd.sh
  runironic.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#68 Whitespace change to trigger a new image build
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#61 Bug 1810078: Copy iPXE binaries directly to /shared at runtime
  Dockerfile.ocp
  prepare-ipxe.sh
  rundnsmasq.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
