Repository openshift/ironic-image, pull requests merged in 2020-08, with the labels that each got.

#97 Bug 1866032: Configure ironic-conductor to auth to ironic-inspector
  configure-ironic.sh
  runironic-api.sh
  runironic-conductor.sh
  runironic.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#99 bug 1859334: Remove all unused modules
  Dockerfile.ocp
  httpd-modules.conf
  httpd.conf
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#100 Install packages from file content
  Dockerfile.ocp
  main-packages-list.txt
Labels: approved, lgtm

#102 Bug 1866123: Use collector name in ironic.conf expected by IPA
  configure-ironic.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#88 bug 1859488: Add the idrac-redfish-virtual-media boot interface
  ironic.conf
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
