Repository openshift/ironic-image, pull requests merged in 2020-12, with the labels that each got.

#127 Add options to disable TLS validations
  configure-ironic.sh
  ironic.conf.j2
Labels: approved, lgtm

#131 Bug 1906397: Fix incorrect IPA option
  ironic.conf.j2
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ¯\_(ツ)_/¯

#129 Bug 1906806: Introduce separate ARG for extra packages list
  Dockerfile.ocp
  prepare-image.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#133 Bug 1909730: Prevent unbound variable error in prepare-image
  prepare-image.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
