Repository openshift/ironic-image, pull requests merged in 2020-11, with the labels that each got.

#121 Ironic log watch cherry-pick
  Dockerfile.ocp
  README.md
  runlogwatch.sh
Labels: approved, lgtm

#114 Bug 1893648: Secure boot compatible ESP image
  Dockerfile.ocp
  ironic.conf.j2
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#119 Bug 1894146: Limit the default number of API workers to 4
  configure-ironic.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#124 Add additional drivers to enabled BIOS interface
  ironic.conf.j2
Labels: approved, lgtm

#126 Merge metal3-io/ironic-inspector-image as of Nov 30, 2020
  Dockerfile.ocp
  OWNERS
  README.md
  configure-ironic.sh
  ironic.conf.j2
  prepare-image.sh
  rundnsmasq.sh
  runmariadb.sh
Labels: approved, lgtm
