Repository openshift/ironic-image, pull requests merged in 2021-07, with the labels that each got.

#189 Add options for external_http_url and external_callback_url
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: approved, lgtm

#188 Support IPA running on top of CoreOS
  Dockerfile.ocp
  Dockerfile.okd
  ironic-config/ironic-python-agent.ign.j2
  ironic-config/ironic.conf.j2
  main-packages-list.txt
  scripts/configure-coreos-ipa
  scripts/configure-ironic.sh
  scripts/coreos-ipa-common.sh
  scripts/runhttpd
Labels: approved, lgtm

#193 Custom deploy: do not require an ISO
  scripts/configure-coreos-ipa
Labels: approved, lgtm

#195 Custom deploy: support custom registry and pull secret
  ironic-config/ironic-python-agent.ign.j2
  scripts/configure-coreos-ipa
Labels: approved, lgtm

#194 Custom deploy: disable TLS host validation in the agent
  ironic-config/ironic-python-agent.ign.j2
Labels: approved, lgtm

#192 Update packages version
  main-packages-list.txt
Labels: approved, lgtm

#190 Sync from metal3-io
  Dockerfile.ocp
  OWNERS
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/httpd-modules.conf
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  main-packages-list.txt
  prepare-image.sh
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/runhttpd
  scripts/runironic-api
  scripts/runironic-conductor
  scripts/runironic-inspector
  scripts/runmariadb
Labels: approved, lgtm

#191 Enable irmc bios interface
  ironic-config/ironic.conf.j2
  main-packages-list.txt
Labels: approved, lgtm, ok-to-test

#196 Custom deploy: do not log the pull secret
  scripts/configure-coreos-ipa
Labels: approved, lgtm

#197 Add inspector callback_endpoint_override
  ironic-config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: approved, lgtm

#200 Bug 1986322: Sync with code from latest bugfix upstream branch
  main-packages-list.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
