Repository openshift/ironic-image, pull requests merged in 2021-06, with the labels that each got.

#175 Bug 1961717: Update remaining out of date deps to Wallaby versions
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#178 Bug 1969212: remove irmc from enabled_bios_interfaces
  config/ironic.conf.j2
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#177 Bug 1897415: Add cipher_suite_versions config
  config/ironic.conf.j2
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#180 Update python-ironic-lib
  main-packages-list.txt
Labels: approved, lgtm

#183 Bug 1972213: Update python-ironic-lib
  main-packages-list.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#152 Revert Wait for expected number of drivers starting API
  scripts/runironic-api
Labels: approved, lgtm

#179 Merge ironic and ironic-inspector repositories
  Dockerfile.ocp
  ironic-config/dnsmasq.conf.j2
  ironic-config/dualboot.ipxe
  ironic-config/httpd-modules.conf
  ironic-config/httpd.conf
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  main-packages-list.txt
  scripts/runhealthcheck
  scripts/runironic-inspector
  scripts/runlogwatch.sh
Labels: approved, lgtm

#176 Add support for deriving the PROVISIONING_INTERFACE from a mac address
  README.md
  scripts/ironic-common.sh
Labels: approved, lgtm

#185 Bug 1975133: [4.9] Sync image with the latest ironic code
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
