Repository openshift/ironic-image, pull requests merged in 2021-01, with the labels that each got.

#134 Bug 1902653: Wait for expected number of drivers starting API
  runironic-api.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#132 Bug 1916145: Explicitly set minimum versions of python libraries
  main-packages-list.txt
  prepare-image.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#139 Bug 1917937: Force rebuild to pick up latest dnsmasq
  main-packages-list.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#140 Bug 1917938: Update dnsmasq version
  main-packages-list.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#138 Bug 1917966: Force update of dnsmasq
  Dockerfile.ocp
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#142 Bug 1915828: Latest Dell firmware (04.40.00.00) fails to install IPI on BM using idrac-virtualmedia protocol
  main-packages-list.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#137 Bug 1920294: Update version of pyghmi library
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#128 Bug 1903649: Re-enable automated_clean
  ironic.conf
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#122 Bug 1899107: Limit the default number of API workers to 4
  configure-ironic.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#143 Bug 1910739: Update ironic version to fix idrac bug
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
