Repository openshift/ironic-image, pull requests merged in 2021-09, with the labels that each got.

#212 Bug 2001519: Don't allow unauthenticated access to Ironic
  ironic-config/apache2-ironic-api.conf.j2
Labels: approved, lgtm

#206 Bug 1991979: [4.8] Sync image with ironic
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#213 OWNERS: add iurygregory, remove stbenjam
  OWNERS
Labels: approved, lgtm

#214 Bug 2003035: Sync sushy to include the latest bugfixes for 4.8
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#208 Rename packages list
  Dockerfile.ocp
  main-packages-list.ocp
Labels: approved, lgtm

#210 Update Dockerfile.okd and add OKD package list
  Dockerfile.okd
  main-packages-list.okd
Labels: approved, lgtm

#215 Sync metal3-io master
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/ironic.conf.j2
  main-packages-list.ocp
  prepare-image.sh
  scripts/runhttpd
  scripts/runironic-inspector
  scripts/runlogwatch.sh
Labels: approved, lgtm

#217 Remove unsafe default for IRONIC_AGENT_IMAGE
  scripts/configure-coreos-ipa
Labels: approved, lgtm
