Repository openshift/ironic-image, pull requests merged in 2021-08, with the labels that each got.

#203 Bug 1989839: Prevent installing docs via a DNF flag
  prepare-image.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#187 Bug 1975137: [4.8] Sync image with the latest ironic code
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#205 Bug 1990316: Fix missing port in iso http url
  scripts/configure-ironic.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#204 Bug 1986238: Supermicro X12 fails to provision using Redfish BM HW Provisioning
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#207 Bug 1993078: Restore auth config to ironic-api
  ironic-config/ironic.conf.j2
  scripts/runironic-api
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#209 Bug 1998528: Sync latest bugfix code
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
