Repository openshift/ironic-image, pull requests merged in 2021-12, with the labels that each got.

#233 Bug 2023765: Compare IPs using the short form of IPv6 address
  main-packages-list.txt
  scripts/ironic-common.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#240 Bring Ironic version to 18.3.0-0.20211206200515.0ff3da2
  main-packages-list.ocp
Labels: approved, lgtm

#243 Don't always pass ignition config in PXE kernel args
  scripts/coreos-ipa-common.sh
Labels: approved, lgtm

#244 Merge metal3io master 20211210
  Dockerfile.ocp
  Dockerfile.okd
  prepare-efi.sh
  prepare-image.sh
  scripts/configure-ironic.sh
Labels: approved, lgtm

#245 Update packages versions to latest stable
  main-packages-list.ocp
Labels: approved, lgtm

#247 Use IPv6-friendly URLs for CoreOS
  scripts/coreos-ipa-common.sh
Labels: approved, lgtm

#246 Disable the node history feature
  ironic-config/ironic.conf.j2
Labels: approved, lgtm

#248 Bug 2032573: Update ironic to include latest major bugfixes
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent
