Repository openshift/ironic-image, pull requests merged in 2021-02, with the labels that each got.

#145 Bug 1918558: Update ironic version with Supermicro boot fix
  main-packages-list.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#141 Bug 1918178: Explicitly set minimum versions of ironic packages
  Dockerfile.ocp
  main-packages-list.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#147 Supply a default for COPY args
  Dockerfile.ocp
Labels: approved, lgtm

#144 Take advantage of multi files COPY to simplify Dockerfile
  Dockerfile.ocp
  config/dnsmasq.conf.j2
  config/httpd-modules.conf
  config/httpd.conf
  config/ironic.conf.j2
  prepare-ipxe.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-api
  scripts/runironic-conductor
  scripts/runironic-exporter
  scripts/runlogwatch.sh
  scripts/runmariadb
Labels: approved, lgtm

#123 Add Support for Fedora-based OKD
  Dockerfile.ocp
  Dockerfile.okd
  config/ironic.conf.j2
Labels: approved, lgtm

#149 Prevent content override of /bin/ when building with imagebuilder
  Dockerfile.ocp
Labels: approved, lgtm

#136 Bug 1917481: Wait for expected number of drivers starting API
  runironic-api.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
