Repository openshift/ironic-image, pull requests merged in 2021-11, with the labels that each got.

#230 Merge metal3 20211102
  ironic-config/ironic-python-agent.ign.j2
  scripts/coreos-ipa-common.sh
Labels: approved, lgtm

#228 Bug 2017412: [4.9] fix Image provisioning fails with file name too long
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#231 Create EFI esp.img on aarch64
  Dockerfile.ocp
  Dockerfile.okd
Labels: approved, lgtm

#235 Install specific version of scciclient
  main-packages-list.ocp
Labels: approved, lgtm

#236 Enable vMedia provisioning of SuperMicro X11/X12
  main-packages-list.ocp
Labels: approved, lgtm

#238 Bug 2025754: Enable vMedia provisioning of SuperMicro X11/X12
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#237 Bug 2025755: Enable vMedia provisioning of SuperMicro X11/X12
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#229 Bug 2017413: [4.8] fix Image provisioning fails with file name too long
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#232 Bug 2023748: Compare IPs using the short form of IPv6 address
  main-packages-list.txt
  scripts/ironic-common.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
