Repository openshift/ironic-image, pull requests merged in 2021-05, with the labels that each got.

#164 Bug 1953979: Add parameter to set boot iso source
  config/ironic.conf.j2
  main-packages-list.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#167 Bug 1957976: update ironic packages for deploy_steps timeout
  main-packages-list.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#169 Bug 1953979: Disable caching live boot iso by default
  scripts/configure-ironic.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#166 Bug 1958965: Updated ironic packages
  main-packages-list.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#168 Bug 1958802: Include fix for CVE-2021-21419
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#170 Bug 1961717: Update dependencies to Wallaby versions
  main-packages-list.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#160 Bug 1963068: Remove ironic entrypoint
  Dockerfile.ocp
  scripts/runironic
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#172 Bug 1962905: Revert "Disable caching live boot iso by default"
  scripts/configure-ironic.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
