Repository openshift/ironic-image, pull requests merged in 2021-03, with the labels that each got.

#150 Start using current ironic versions
  main-packages-list.txt
Labels: approved, lgtm

#155 Bug 1937695: Supply a default for COPY args
  Dockerfile.ocp
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#154 Bug 1888712: Support for including vlan interfaces in introspection r…
  config/inspector.ipxe.j2
  config/ironic.conf.j2
  scripts/configure-ironic.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#156 Update packages to pick up latest changes
  main-packages-list.txt
Labels: approved, lgtm
