Repository openshift/ironic-image, pull requests merged in 2022-11, with the labels that each got.

#309 OCPBUGS-2992: Don't save OS_ prefixed variables
  scripts/configure-ironic.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#308 Add DNS or GW for use by dnsmasq
  README.md
  ironic-config/dnsmasq.conf.j2
  scripts/rundnsmasq
Labels: approved, lgtm

#313 Bug OCPBUGS-3480: Improve resiliency of eTag handling
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, jira/severity-important, jira/valid-bug

#315 [4.12] Bug OCPBUGS-3479: Improve resiliency of eTag handling
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, jira/severity-important, jira/valid-bug

#304 Allow dnsmasq to work as a DNS forwarder
  ironic-config/dnsmasq.conf.j2
  scripts/rundnsmasq
Labels: approved, lgtm

#321 OCPBUGS-1844: Merge from upstream metal3-io/ironic-image
  README.md
  ironic-config/dnsmasq.conf.j2
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/rundnsmasq
  scripts/runhttpd
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#319 OCPBUGS-3085: Workaround for long time gap between operations in recent idrac
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#320 Add support for OKD/SCOS
  Dockerfile.fcos
  Dockerfile.okd
  Dockerfile.scos
  ironic-config/ironic.conf.j2
  main-packages-list.okd
Labels: approved, lgtm

#325 Bug OCPBUGS-4225: Fix setting boot related attributes
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#326 Bug OCPBUGS-4305: Remove RDO distribution configuration (finally fixes #46)
  prepare-image.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
