Repository openshift/ironic-image, pull requests merged in 2022-08, with the labels that each got.

#286 METAL-256: Add a new entry point for the Ironic proxy
  Dockerfile.ocp
  Dockerfile.okd
  ironic-config/apache2-proxy.conf.j2
  scripts/runironic-proxy
Labels: approved, lgtm

#289 Merge from upstream metal3-io/ironic-image
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/ironic-python-agent.ign.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic-inspector
Labels: approved, lgtm

#291 OCPBUGS-171: Fix IRONIC_EXTERNAL_IP when TLS is used for virtual media
  scripts/configure-ironic.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#292 ironic-proxy: never validate TLS peer name
  ironic-config/apache2-proxy.conf.j2
Labels: approved, lgtm

#290 Update dependencies for OCP 4.12
  main-packages-list.ocp
Labels: approved, lgtm

#293 Update ironic and ironic-inspector for OCP 4.12
  main-packages-list.ocp
Labels: approved, lgtm

#285 Bug 2110407: ignore case of mac address
  scripts/ironic-common.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#296 Bug 2104275: sync the ValueDisplayName fix
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
