Repository openshift/ironic-image, pull requests merged in 2022-10, with the labels that each got.

#305 Removed ServerName from VirtualHost Directives
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/apache2-proxy.conf.j2
  ironic-config/apache2-vmedia.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
Labels: approved, lgtm

#302 OCPBUGS-2011: Backport improvements to iDRAC steps to OCP 4.11
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#303 OCPBUGS-1740: Backport improvements to iDRAC steps to OCP 4.10
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#306 OCPBUGS-1972: Removed ServerName from VirtualHost Directives
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/apache2-vmedia.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
