Repository openshift/ironic-image, pull requests merged in 2022-09, with the labels that each got.

#295 OCPBUGS-528: Fix IRONIC_EXTERNAL_IP when TLS is used for virtual media
  scripts/configure-ironic.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug

#297 OCPBUGS-746: sync fixes for BIOS settings on SMC
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#299 Update sushy to 4.3.0 (Zed final)
  main-packages-list.ocp
Labels: approved, lgtm

#298 OCPBUGS-1225: sync BIOS settings fixes
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#300 OCPBUGS-1799: use brackets for IPv6 addresses in ironic-proxy
  scripts/runironic-proxy
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#301 Sync with upstream metal3-io ironic-image 2022-09-29
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
Labels: approved, lgtm
