Repository openshift/ironic-image, pull requests merged in 2022-03, with the labels that each got.

#256 Update packages with latest available
  main-packages-list.ocp
Labels: approved, lgtm

#257 Bug 2059567: Enable vMedia provisioning of Nokia servers
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#259 Sync with metal3-io/main
  ironic-config/ironic.conf.j2
  prepare-efi.sh
Labels: approved, lgtm

#261 Correct version for sushy-oem-idrac for OCP 4.11
  main-packages-list.ocp
Labels: approved
