Repository openshift/ironic-image, pull requests merged in 2022-12, with the labels that each got.

#314 [4.11] Bug OCPBUGS-3478: Improve resiliency of eTag handling
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#316 [4.10] Bug OCPBUGS-3477: Improve resiliency of eTag handling
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#333 OCPBUGS-4492: Handle a different error code for missing TransferProtocolType
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#332 OCPBUGS-4635: Update packages versions with latest available
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#317 [4.9] Bug OCPBUGS-1246: Improve resiliency of eTag handling
  main-packages-list.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#334 OCPBUGS-4840: Handle a different error code for missing TransferProtocolType
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#335 OCPBUGS-4789: Update packages versions with latest available
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#338 OCPBUGS-5068: Configure Ironic iLO driver to use web server
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#340 OCPBUGS-5136: Adding dosfstools and util-linux tools to ironic-image
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low
