Repository openshift/ironic-image, pull requests merged in 2022-07, with the labels that each got.

#281 Bug 2087213: Ironic Fix for ZTP with 4.11
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, qe-approved

#283 Sync with upstream metal3-io ironic-image
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/ironic-common.sh
  scripts/runhttpd
Labels: approved, lgtm

#284 Bug 2109125: Upgrade version of ironic package to include fix for ZTP deployment
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed
