Repository openshift/ironic-image, pull requests merged in 2023-04, with the labels that each got.

#354 Merge from upstream metal3-io/ironic-image
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  README.md
  configure-nonroot.sh
  prepare-image.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
Labels: approved, lgtm

#353 OCPBUGS-8068: Fix for node's last_error disappears briefly on cleaning failure
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#357 OCPBUGS-10701: Update sushy to 4.5.0 to handle ZT servers
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#359 Update sushy with latest changes
  main-packages-list.ocp
Labels: approved, lgtm

#355 OCPBUGS-10343: allow inspector to also be proxied
  ironic-config/apache2-proxy.conf.j2
  scripts/runironic-proxy
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#356 OCPBUGS-7565: Adding dep on python3-werkzeug >= 2.0.3-4
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#360 Sync with latest packages available
  main-packages-list.ocp
Labels: approved, lgtm

#362 OCPBUGS-12703: Bump python-sushy
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
