Repository openshift/ironic-image, pull requests merged in 2023-10, with the labels that each got.

#395 Sync20230829
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  README.md
  ironic-config/apache2-vmedia.conf.j2
  ironic-config/httpd-ironic-api.conf.j2
  ironic-config/httpd-modules.conf
  ironic-config/httpd.conf
  ironic-config/httpd.conf.j2
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic-python-agent.ign.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/configure-coreos-ipa
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-api
Labels: approved, lgtm

#405 Revert #395 "Sync20230829"
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  README.md
  ironic-config/apache2-ironic-api.conf.j2
  ironic-config/apache2-vmedia.conf.j2
  ironic-config/httpd-modules.conf
  ironic-config/httpd.conf
  ironic-config/httpd.conf.j2
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic-python-agent.ign.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/configure-coreos-ipa
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-api
Labels: approved, lgtm

#404 OCPBUGS-19884: update Ironic to include secure boot fixes
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#409 OCPBUGS-21849: bump eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#408 OCPBUGS-21876: Use bash process substitution instead of pipe
  scripts/ironic-common.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#410 OCPBUGS-21847: Bump eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
