Repository openshift/ironic-image, pull requests merged in 2023-12, with the labels that each got.

#430 OCPBUGS-23978: Ironic side of external_http_url (METAL-163) is not wired in correctly
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#434 NO-ISSUE: Update ironic packages version
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference

#431 OCPBUGS-23979: Ironic side of external_http_url (METAL-163) is not wired in correctly
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#435 OCPBUGS-9303: include the secure boot retry
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#437 NO-ISSUE: Add requirements placeholders for cachito
  requirements-build.cachito
  requirements.cachito
  setup.cfg
  setup.py
Labels: approved, lgtm, jira/valid-reference

#443 NO-ISSUE: Merge from metal3-io/ironic-image (33275f5)
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  README.md
  configure-nonroot.sh
  ironic-config/apache2-ipxe.conf.j2
  ironic-config/dnsmasq.conf.j2
  ironic-config/httpd-ironic-api.conf.j2
  ironic-config/ipxe_config.template
  ironic-config/ironic.conf.j2
  scripts/auth-common.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-inspector
  scripts/tls-common.sh
Labels: approved, lgtm, jira/valid-reference

#441 OCPBUGS-25605: Relax packages requirements
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#442 OCPBUGS-25606: Relax packages requirements
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
