Repository openshift/ironic-image, pull requests merged in 2023-11, with the labels that each got.

#407 METAL-730: Sync202310
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  README.md
  ironic-config/apache2-vmedia.conf.j2
  ironic-config/httpd-ironic-api.conf.j2
  ironic-config/httpd-modules.conf
  ironic-config/httpd.conf
  ironic-config/httpd.conf.j2
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic-python-agent.ign.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  scripts/configure-coreos-ipa
  scripts/configure-httpd-ipa.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhttpd
  scripts/runironic
  scripts/runironic-api
Labels: approved, lgtm, jira/valid-reference

#412 METAL-726: Update packages for OCP 4.15 and pin ironic versions
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference

#415 OCPBUGS-14926: Handle Eject DVD 4.14
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#413 OCPBUGS-23072: Use bash process substitution instead of pipe
  scripts/ironic-common.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#416 OCPBUGS-19078: Handle Eject DVD 4.13
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#417 OCPBUGS-19064: Handle Eject DVD in 4.12
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#420 OCPBUGS-22425: Upgrade markupsafe and werkzeug dependencies
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#421 OCPBUGS-23354: Upgrade markupsafe and werkzeug dependencies
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#422 OCPBUGS-23356: Upgrade werkzeug dependency
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#425 OCPBUGS-23485: Uplift eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#423 OCPBUGS-23357: Upgrade werkzeug dependency
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#426 OCPBUGS-23505: Uplift eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#427 OCPBUGS-23506: Uplift eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#428 OCPBUGS-23939: Firmware interface
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
