Repository openshift/ironic-image, pull requests merged in 2023-08, with the labels that each got.

#387 OCPBUGS-17142: [4.14] Update packages with latest bugfix
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#389 OCPBUGS-17472: Expand regex for fcos/okd packages list
  Dockerfile.fcos
  Dockerfile.scos
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#391 OCPBUGS-14795: Bumping package versions to include 100823 upstream sync.
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#388 OCPBUGS-17158: [4.13] Update packages with latest bugfix
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#393 OCPBUGS-17837: Fix PROVISIONING_MACS unbound
  scripts/ironic-common.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#394 OCPBUGS-14926: Bumping versions to include packages synced on 180823.
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#396 OCPBUGS-18297: Revert "Bumping versions to include packages synced on…
  main-packages-list.ocp
Labels: approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
