Repository openshift/ironic-image, pull requests merged in 2023-01, with the labels that each got.

#336 OCPBUGS-4908: Update packages versions with latest available
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#344 [4.11] Bug OCPBUGS-5404: Adding dosfstools and util-linux tools to ironic-image
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low

#345 OCPBUGS-5415: Update packages versions with latest available
  main-packages-list.ocp
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#346 OCPBUGS-5461: Add ironic IP to no_proxy
  scripts/configure-ironic.sh
  scripts/runironic-inspector
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug
