Repository openshift/ironic-image, pull requests merged in 2023-09, with the labels that each got.

#398 OCPBUGS-19019: Switch from current-tripleo to puppet-passed-ci
  Dockerfile.fcos
  Dockerfile.scos
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#401 OCPBUGS-18963: update ironic to include SQLite fixes
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#402 OCPBUGS-19333: update ironic to include SQLite fixes
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#403 OCPBUGS-9303: update Ironic to include secure boot fixes
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
