Repository openshift/ironic-image, pull requests merged in 2024-01, with the labels that each got.

#445 OCPBUGS-19884: update Ironic to include secure boot fixes
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#446 OCPBUGS-22699: Fix Inspector iPXE config for IPv6 addresses
  ironic-config/inspector.ipxe.j2
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#449 METAL-850: Update packages for OCP 4.16
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference

#448 [release-4.14] OCPBUGS-27193: Fix Inspector iPXE config for IPv6 addresses
  ironic-config/inspector.ipxe.j2
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#451 OCPBUGS-27967: Update packages for OCP 4.16
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#450 OCPBUGS-27772: Update packages to include most recent bug fixes
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
