Repository openshift/ironic-image, pull requests merged in 2024-04, with the labels that each got.

#466 METAL-952: Install sushy from source
  main-packages-list.ocp
  requirements.cachito
  tools/check-requirements.sh
Labels: approved, lgtm, jira/valid-reference

#464 METAL-949: Force pysnmp-lextudio and pyasn1 min version
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#470 OCPBUGS-31830,OCPBUGS-31686,OCPBUGS-31802: [4.15] install ironic projects from source
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  Makefile
  main-packages-list.ocp
  main-packages-list.okd
  prepare-image.sh
  requirements.cachito
  tools/check-requirements.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#471 OCPBUGS-32162: Bump eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#472 OCPBUGS-32390: Use unix sockets by default for reverse proxy communication
  scripts/ironic-common.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#474 OCPBUGS-32389: Use unix sockets by default for reverse proxy communication
  scripts/ironic-common.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#469 OCPBUGS-32169: [4.14] Add requirements placeholders for cachito
  requirements-build.cachito
  requirements.cachito
  setup.cfg
  setup.py
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#475 OCPBUGS-32388: Use unix sockets by default for reverse proxy communication
  scripts/ironic-common.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#476 OCPBUGS-32387: Use unix sockets by default for reverse proxy communication
  scripts/ironic-common.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#477 OCPBUGS-32386: Use unix sockets by default for reverse proxy communication
  scripts/ironic-common.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#478 OCPBUGS-32350: Update to include fixes for ironic servicing feature
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#481 NO-ISSUE: Use microversion-parse package
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#480 OCPBUGS-32366: [4.16] Bump gunicorn version
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#482 OCPBUGS-32169: [4.14] Add hybrid configuration for cachito
  Dockerfile.fcos
  Dockerfile.ocp
  Dockerfile.scos
  Makefile
  main-packages-list.ocp
  main-packages-list.okd
  prepare-image.sh
  requirements.cachito
  tools/check-requirements.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#479 OCPBUGS-32351: [4.15] Update to include fixes for ironic servicing feature
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#484 OCPBUGS-32366: [4.16] Remove unused prometheus exporter
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#473 NO-ISSUE: Merge from metal3-io/ironic-image
  README.md
  configure-nonroot.sh
  ironic-config/httpd-ironic-api.conf.j2
  ironic-config/httpd-modules.conf
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic.conf.j2
  main-packages-list.ocp
  main-packages-list.okd
  scripts/auth-common.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/ironic-probe.j2
  scripts/runironic
  scripts/runironic-api
  scripts/runironic-conductor
Labels: approved, lgtm, jira/valid-reference

#485 OCPBUGS-32365: [4.15] Remove unused prometheus exporter
  main-packages-list.ocp
  main-packages-list.okd
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#487 OCPBUGS-32364: [4.14] remove unused prometheus-exporter
  main-packages-list.ocp
  main-packages-list.okd
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#488 OCPBUGS-32363: [4.13] remove unused prometheus-exporter
  Dockerfile.fcos
  Dockerfile.scos
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#489 OCPBUGS-32362: [4.12] remove unused prometheus-exporter
  Dockerfile.fcos
  Dockerfile.scos
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
