Repository openshift/ironic-image, pull requests merged in 2024-08, with the labels that each got.

#534 [4.16] OCPBUGS-33376: bump werkzeug
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#530 [4.14] OCPBUGS-37410: bump jinja2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#538 [4.13] OCPBUGS-34898: bump jinja2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#536 [4.15] OCPBUGS-33332: bump werkzeug
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#541 [4.12] OCPBUGS-34897: bump jinja2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#542 OCPBUGS-38406: Update root image
  .ci-operator.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#540 OCPBUGS-38077: update sushy to pick up the RAID fix
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#537 [4.14] OCPBUGS-33375: bump werkzeug
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#544 METAL-1123: Suppress file listing of compiled py files
  prepare-image.sh
Labels: approved, lgtm, jira/valid-reference

#543 [4.13] OCPBUGS-33374: bump werkzeug
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#546 OCPBUGS-38481: Update root image
  .ci-operator.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#556 OCPBUGS-38596: Update ironic version in ironic-image
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#547 [4.12] OCPBUGS-33373: bump werkzeug
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#550 OCPBUGS-38521: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#545 OCPBUGS-38465: update sushy to pick up the RAID fix
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#560 OCPBUGS-38782: redfish-virtualmedia fails on XFusion nodes
  requirements.cachito
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#566 NO-ISSUE: fix scos and fcos dockerfiles to remove ironic-inspector
  Dockerfile.fcos
  Dockerfile.scos
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#559 OCPBUGS-36492: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#561 OCPBUGS-38596: Update ironic commit hash
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#568 OCPBUGS-39013: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
