Repository openshift/ironic-image, pull requests merged in 2024-09, with the labels that each got.

#572 [4.17] OCPBUGS-38784: Update sushy to include Huwaei Fix ( Duplicate PR )
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#574 OCPBUGS-35895: Sync from upstream 2024-08-21 #563
  ironic-config/httpd.conf.j2
  ironic-config/ironic.conf.j2
  prepare-image.sh
  scripts/configure-ironic.sh
  scripts/tls-common.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#575 OCPBUGS-41196: Include fixes for CVE-2024-44082
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#552 [4.17] OCPBUGS-38511: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#573 OCPBUGS-37365: Update log statement to avoid logging entire node object
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#576 OCPBUGS-39380: Include fixes for CVE-2024-44082 into 4.17
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#578 OCPBUGS-41783: Set node "alive" when inspection finished
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#553 [4.16] OCPBUGS-38510: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#554 [4.15] OCPBUGS-38512: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#579 OCPBUGS-39383,OCPBUGS-37758: Include fixes for CVE-2024-44082
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#555 [4.14] OCPBUGS-38508: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#583 OCPBUGS-39381,OCPBUGS-37761: Include fixes for CVE-2024-44082
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#587 OCPBUGS-42113: Update ironic-inspector to fix the memory leak
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#564 [4.16] OCPBUGS-38797: redfish-virtualmedia fails on XFusion nodes
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#557 [4.13] OCPBUGS-38509: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#584 OCPBUGS-39382,OCPBUGS-37762: Include fixes for CVE-2024-44082
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
