Repository openshift/ironic-image, pull requests merged in 2024-11, with the labels that each got.

#602 OCPBUGS-43959, OCPBUGS-43951: Bump python-waitress
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#603 OCPBUGS-43963, OCPBUGS-43955: Bump python-waitress [4.17]
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#604 OCPBUGS-43958, OCPBUGS-43950: Bump python-waitress [4.16]
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#605 OCPBUGS-43953, OCPBUGS-43961: Bump python-waitress [4.15]
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#606 NO-ISSUE: Update ironic projects 2024-11-12
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#607 OCPBUGS-43954, OCPBUGS-43962: Bump python-waitress [4.14]
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#608 OCPBUGS-43952, OCPBUGS-43960: Bump python-waitress [4.13]
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#609 OCPBUGS-43949, OCPBUGS-43957: Bump python-waitress [4.12]
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
