Repository openshift/ironic-image, pull requests merged in 2024-07, with the labels that each got.

#494 METAL-1049: Download and install sources from local dir
  prepare-image.sh
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#519 OCPBUGS-33335: Update Python Jinja2
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#521 [4.16] OCPBUGS-36838: Update Jinja2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#520 METAL-1070: Align ironic dependencies with latest upper constraints
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference

#522 OCPBUGS-37084: Update ironic projects to latest available
  requirements.cachito
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference, acknowledge-critical-fixes-only

#523 OCPBUGS-37113: Update eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#524 OCPBUGS-37115: Update eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#525 OCPBUGS-37116: Update eventlet version
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#532 METAL-1094: Sync with upstream metal3-io/ironic-image
  .gitignore
  Dockerfile.ocp
  Makefile
  README.md
  configure-nonroot.sh
  ironic-config/apache2-proxy.conf.j2
  ironic-config/inspector.ipxe.j2
  ironic-config/ironic.conf.j2
  ironic-inspector-config/inspector-apache.conf.j2
  ironic-inspector-config/ironic-inspector.conf.j2
  prepare-image.sh
  requirements.cachito
  scripts/auth-common.sh
  scripts/configure-ironic.sh
  scripts/ironic-common.sh
  scripts/runhealthcheck
  scripts/runhttpd
  scripts/runironic-inspector
  scripts/runironic-proxy
  scripts/runlogwatch.sh
  scripts/tls-common.sh
  tools/check-requirements.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#533 OCPBUGS-37402: bump werkzeug
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#529 [4.15] OCPBUGS-37407: bump jinja2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
