Repository openshift/ironic-image, pull requests merged in 2024-10, with the labels that each got.

#558 [4.12] OCPBUGS-38513: set min version for python3-webob
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#565 [4.15] OCPBUGS-38798: redfish-virtualmedia fails on XFusion nodes
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#585 OCPBUGS-39384,OCPBUGS-37764: Include fixes for CVE-2024-44082
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#548 [4.14] OCPBUGS-32266: redfish-virtualmedia fails on XFusion nodes
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#586 OCPBUGS-39385,OCPBUGS-37766: Include fixes for CVE-2024-44082
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#589 OCPBUGS-36832: Include fixes for CVE-2024-5569
  main-packages-list.ocp
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#570 OCPBUGS-39018: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#592 OCPBUGS-42510: Include fix for CVE-2024-47211
  requirements.cachito
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#597 METAL-1155: Remove wheel after build is done
  prepare-image.sh
Labels: approved, lgtm, jira/valid-reference

#571 OCPBUGS-39019: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#598 METAL-1164: Add pip no-build-isolation to download command
  prepare-image.sh
Labels: approved, lgtm, jira/valid-reference

#588 METAL-1118: Update dependencies for OCP 4.18
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference

#593 OCPBUGS-42509: Include fix for CVE-2024-47211
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#590 [4.17] OCPBUGS-42692: Include fixes for CVE-2024-5569
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#594 OCPBUGS-42511: Include fix for CVE-2024-47211
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#599 [4.16] OCPBUGS-43438: Include fixes for CVE-2024-5569
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#600 NO-ISSUE: Update ironic projects hashes
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference
