Repository openshift/ironic-image, pull requests merged in 2024-06, with the labels that each got.

#508 Bug OCPBUGS-34534: Disable installation of .pyc files through pip
  prepare-image.sh
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#511 [4.15] Bug OCPBUGS-33736: Disable installation of .pyc files through pip
  prepare-image.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#513 OCPBUGS-29687: Read ironic and inspector htpasswds from files
  scripts/auth-common.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#512 [4.14] Bug OCPBUGS-34657: Disable installation of .pyc files through pip
  prepare-image.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#514 NO-ISSUE: Bump ironic projects versions
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#516 OCPBUGS-32261: Update ironic-inspector to fix the memory leak
  requirements.cachito
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
