Repository openshift/ironic-image, pull requests merged in 2025-09, with the labels that each got.

#684 OCPBUGS-60455: set [json_rpc]port unconditionally
  ironic-config/ironic.conf.j2
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified

#688 OKD-283: fixing OKD ironic-image errors and metal3 pod crashes (centos9)
  Dockerfile.ocp
  Dockerfile.scos
  Makefile
  main-packages-list.okd
  prepare-image.sh
  python-requirements.okd
Labels: approved, lgtm, jira/valid-reference, verified

#692 METAL-1574: Remove temporary dependencies from source
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference, verified

#695 METAL-1566,METAL-1577,METAL-1446: Sync Ironic and Sushy
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference, verified

#696 OKD-290: (OKD4.20) Fix ironic-image errors and metal3 pod crashes on CentOS9
  Dockerfile.ocp
  Dockerfile.scos
  Makefile
  main-packages-list.okd
  prepare-image.sh
  python-requirements.okd
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#697 OCPBUGS-62201: Bump ironic to include idrac10 fix
  requirements.cachito
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference, verified
