Repository openshift/ironic-image, pull requests merged in 2025-07, with the labels that each got.

#666 OCPBUGS-56755,OCPBUGS-57454: Bump sushy and ironic commit
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#667 OCPBUGS-55298: Bump ironic to latest
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#668 METAL-1496: Revert "OCPBUGS-55298: Bump ironic to latest"
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#658 METAL-1414: Use Python 3.12 to build and run ironic
  ironic-config/ironic.conf.j2
  main-packages-list.ocp
  prepare-image.sh
  scripts/ironic-common.sh
  scripts/rundnsmasq
  scripts/runhttpd
  scripts/runironic
  scripts/runlogwatch.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#672 METAL-1379: Bump ironic to include NIC Firmware Updates
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#674 METAL-1461: update config to allow Ironic to work with ironic-prometheus-exporter
  README.md
  ironic-config/ironic.conf.j2
  scripts/runironic-exporter
Labels: approved, lgtm, jira/valid-reference
