Repository openshift/ironic-image, pull requests merged in 2025-03, with the labels that each got.

#641 OCPBUGS-51310: Fix runlogwatch script
  scripts/runlogwatch.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#642 OCPBUGS-52290: Fix runlogwatch script
  scripts/runlogwatch.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#643 OCPBUGS-52292: Fix runlogwatch script
  scripts/runlogwatch.sh
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#645 METAL-1299: Do not use openstack packages
  Dockerfile.ocp
Labels: approved, lgtm, jira/valid-reference

#644 METAL-1297: Update ironic-image to the latest commit hash
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#646 METAL-1302: Do not use openstack packages
  Dockerfile.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#647 METAL-1305: Do not use openstack packages
  Dockerfile.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#648 METAL-1306: Do not use openstack packages
  Dockerfile.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#650 NO-JIRA: Sync with upstream metal3/main 2025-03-24
  scripts/auth-common.sh
  scripts/configure-ironic.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#649 NO-ISSUE: Update dependencies for OCP 4.19, part 1
  main-packages-list.ocp
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
