Repository openshift/ironic-image, pull requests merged in 2025-01, with the labels that each got.

#614 OCPBUGS-45636: Sync including fix for bug
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#618 OCPBUGS-48172: Bump jinja2 to 3.1.5
  main-packages-list.ocp
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#619 METAL-1251: Remove dependency from ironic-lib
  requirements.cachito
  tools/check-requirements.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#620 [4.18] OCPBUGS-48150: Bump jinja2 to 3.1.5
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#622 [4.17] OCPBUGS-48149: Bump jinja2 to 3.1.5
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#621 METAL-1253: Remove dependency from sushy package
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#623 [4.16] OCPBUGS-48151,OCPBUGS-48598: Bump jinja2 to 3.0.1-6.el9.2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#624 [4.15] OCPBUGS-48148,OCPBUGS-48597: Bump jinja2 to 3.0.1-6.el9.2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#625 [4.14] OCPBUGS-48147,OCPBUGS-48594: Bump jinja2 to 3.0.1-6.el9.2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#626 [4.13] OCPBUGS-48146,OCPBUGS-48595: Bump jinja2 to 3.0.1-6.el9.2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#615 OCPBUGS-45637: Ensure ironic caches node information
  main-packages-list.ocp
  requirements.cachito
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#627 [4.12] OCPBUGS-48145,OCPBUGS-48596: Bump jinja to 3.0.1-6.el9.2
  main-packages-list.ocp
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#628 METAL-1266: Switch master branch to main in check-requirements
  tools/check-requirements.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
