Repository openshift/ironic-image, pull requests merged in 2025-05, with the labels that each got.

#654 OCPBUGS-55381: Extract files one-by-one in logwatch
  scripts/runlogwatch.sh
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#655 METAL-1264: Update to latest upstream content
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference

#653 METAL-1344: Do not install sushy-oem-idrac separately
  requirements.cachito
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#659 Bug OCPBUGS-55434: Bump sushy to include SuperMicro boot device string workaround
  requirements.cachito
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference
